version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodbdata:

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
      - redis
